<script lang="ts">
  import { NEW_NOTES_1_ALL, NEW_MODES, SCALE_DEGREE_NUMERALS } from '$lib/utils/sounds';
  import { COLOR_PALETTES }                                      from '$lib/utils/colors';
  import { ZODIAC_CONSTELLATIONS, WANDERING_STARS }             from '$lib/utils/stars';

  // ── Synthesis table data ───────────────────────────────────────────────────
  // Derived at module load — the three systems can never diverge from each other
  // or from the essay's claim: same index, same correspondence, always in sync.

  const circleOfTwelve = NEW_NOTES_1_ALL.map((note, i) => ({
    note,
    color:    COLOR_PALETTES.wheel[i].name,
    colorVar: COLOR_PALETTES.wheel[i].variable,
    zodiac:   ZODIAC_CONSTELLATIONS[i],
  }));

  const sequenceOfSeven = NEW_MODES.map((mode, i) => ({
    numeral: SCALE_DEGREE_NUMERALS[i],
    mode,
    star:    WANDERING_STARS[i],
  }));
</script>

<article>

  <h1 class="title">Design Monolith</h1>
  <p class="subtitle">An Audio-Visual Design System of Order Against Chaos</p>

  <img src="/images/Paradiso_Canto_31_(148200393).jpg" alt="Paradiso" />

  <!-- ══════════════════════════════════════ -->
  <!-- I. THE FIRST SONG                      -->
  <!-- ══════════════════════════════════════ -->
  <h2>The First Song</h2>

  <p>One "Hertz" is equal to one single heartbeat cycle of a healthy human being. The origin is the heart — the heartbeat itself.</p>

  <img src="/images/Holy card depicting the Sacred Heart of Jesus, c. 1880.jpg" alt="Sacred Heart of Jesus" />

  <p>When an open string is plucked, a sound, a note, is produced. When that same string is pressed at its midpoint and plucked again, a different pitch emerges — the same note, but at double the frequency. This is the 1:2 ratio, which produces the <em>octave</em>.</p>

  <p>Playing the same note is the most harmonious thing one can do, yet it is monotone. Playing it at different octaves is equally harmonious, and slightly more varied — yet still quite monotone.</p>

  <p>How, then, does a new note come into being?</p>

  <p>The next simplest ratio after 1:2 is 2:3. When a string is pressed at its third and plucked, a new note is produced. This 2:3 ratio yields the <em>pure perfect fifth</em> — the most consonant interval after the octave. These two ratios are the backbone of music.</p>

  <p>Neither is a discovery. Plato, in his <em>Timaeus</em>, describes the world itself as constructed from these same two proportions — the 1:2 of the octave and the 2:3 of the fifth. What follows builds upon that foundation.</p>

  <hr />

  <!-- ══════════════════════════════════════ -->
  <!-- II. THE CIRCLE OF TWELVE               -->
  <!-- ══════════════════════════════════════ -->
  <h2>The Circle of Twelve</h2>

  <p>As established in the preceding section, two is the number of duplication, and three is the number of creation.</p>

  <p>Beginning from the first note of 1 Hz, the remaining eleven are generated by successive multiplication by the ratio 3:2:</p>

  <ul>
    <li>1st note: 1 Hz</li>
    <li>2nd note: 1 × 3/2 = 1.5 Hz</li>
    <li>3rd note: 1.5 × 3/2 = 2.25 Hz</li>
    <li>4th note: 2.25 × 3/2 = 3.375 Hz</li>
    <li>5th note: 3.375 × 3/2 = 5.0625 Hz</li>
    <li>6th note: 5.0625 × 3/2 = 7.59375 Hz</li>
    <li>7th note: 7.59375 × 3/2 = 11.390625 Hz</li>
    <li>8th note: 11.390625 × 3/2 = 17.0859375 Hz</li>
    <li>9th note: 17.0859375 × 3/2 = 25.62890625 Hz</li>
    <li>10th note: 25.62890625 × 3/2 = 38.443359375 Hz</li>
    <li>11th note: 38.443359375 × 3/2 = 57.6650390625 Hz</li>
    <li>12th note: 57.6650390625 × 3/2 = 86.49755859375 Hz</li>
  </ul>

  <p>These twelve notes nearly divide the circle into equal parts, which is supremely practical. The division is not perfectly equal because music is, in truth, a spiral — not a circle. The next close division afforded by the 3:2 ratio falls at 53 parts, which is impractical for performance.</p>

  <p>Equivalently, these twelve notes arise from successive powers of three:</p>

  <p>3⁰ = C,  3¹ = G,  3² = D,  3³ = A,  3⁴ = E,  3⁵ = B,  3⁶ = F♯,  3⁷ = C♯,  3⁸ = G♯,  3⁹ = D♯,  3¹⁰ = A♯,  3¹¹ = F.</p>

  <p>When arranged by proximity of pitch, the <em>chromatic circle</em> is formed: C–C♯–D–D♯–E–F–F♯–G–G♯–A–A♯–B  (0–1–2–3–4–5–6–7–8–9–10–11).</p>

  <p>When arranged in the order of their generation, the <em>circle of fifths</em> is formed: C–G–D–A–E–B–F♯–C♯–G♯–D♯–A♯–F  (0–7–2–9–4–11–6–1–8–3–10–5).</p>

  <p>According to the circle of fifths, one ought to be able to travel by a perfect fifth exactly twelve times and return to the note from which the journey began — one octave higher. However, (3:2)¹² = 129.746337891, which is not equal to 2⁷ = 128. The difference of 1.746337891 makes such a return impossible, and that twelfth interval is dissonant.</p>

  <p>This discrepancy is known as the <em>Pythagorean comma</em>. The imperfect interval it produces has been called the <em>wolf fifth</em>, the <em>Procrustean fifth</em>, or simply the <em>imperfect fifth</em>.</p>

  <img src="/images/Gaffurio_Pythagoras.png" alt="Pythagoras" />

  <p>The contemporary remedy is <em>equal temperament</em> — a system that resolves the comma by dividing the octave into twelve steps of identical frequency ratio. In doing so, it introduces a far graver problem: a musical system of pervasive, subtle dissonance to which modern ears have simply grown accustomed. This is a satanic lie of harmony — chaos in disguise.</p>

  <p>The Pythagorean comma is not a flaw to be corrected; it is a golden rule — a natural boundary declaring that a musical scale should contain a maximum of seven notes.</p>

  <p>Such a scale is nothing new under the Sun. It is called the <em>Pythagorean scale</em>, constructed entirely from pure perfect fifths.</p>

  <p>In the chromatic circle, a Pythagorean scale follows the pattern 0–2–4–6–7–9–11, or the interval sequence W–W–W–H–W–W–H, where W denotes a whole tone and H a semitone. In the circle of fifths, it is simply seven adjacent notes: 0–1–2–3–4–5–6. The zero in both patterns represents the <em>root note</em> of the scale.</p>

  <p>Beginning from each of the seven degrees, the seven <em>musical modes</em> arise. A mode is a class of scales sharing the same interval pattern:</p>

  <ul>
    <li>Mode I (from the 1st degree) — W–W–W–H–W–W–H — <em>Lydian</em></li>
    <li>Mode II (from the 2nd degree) — W–W–H–W–W–H–W — <em>Mixolydian</em></li>
    <li>Mode III (from the 3rd degree) — W–W–H–W–W–W–H — <em>Aeolian</em></li>
    <li>Mode IV (from the 4th degree) — H–W–W–H–W–W–W — <em>Locrian</em></li>
    <li>Mode V (from the 5th degree) — W–W–H–W–W–W–H — <em>Ionian</em></li>
    <li>Mode VI (from the 6th degree) — W–H–W–W–W–H–W — <em>Dorian</em></li>
    <li>Mode VII (from the 7th degree) — H–W–W–W–H–W–W — <em>Phrygian</em></li>
  </ul>

  <p>Thus, the first scale is the Lydian mode rooted on C: C–D–E–F♯–G–A–B, or expressed through the circle of fifths: C–G–D–A–E–B–F♯.</p>

  <hr />

  <!-- ══════════════════════════════════════ -->
  <!-- III. THE ASCENDING SPIRAL              -->
  <!-- ══════════════════════════════════════ -->
  <h2>The Ascending Spiral</h2>

  <p>A genuine difficulty arises when constructing certain scales.</p>

  <p>The F Lydian scale offers the clearest example. It begins on F, at a frequency of 3¹¹ Hz. Its subsequent notes are:</p>

  <ul>
    <li>C, at 3¹²</li>
    <li>G, at 3¹³</li>
    <li>D, at 3¹⁴</li>
    <li>A, at 3¹⁵</li>
    <li>E, at 3¹⁶</li>
    <li>B, at 3¹⁷</li>
  </ul>

  <p>These pitches are close — but not identical — to their counterparts among the original twelve. For this reason they are named with the suffix <em>x</em> (as in <em>extra</em>): Cx, Gx, Dx, Ax, Ex, Bx.</p>

  <p>The smallest such discrepancy, for C, is:</p>
  <p>3¹² / 2¹⁹ − 1 = 7153 / 524288</p>

  <p>This difference accumulates when stacking twelve or more pure fifths and comparing the results to the same tones at lower octaves. Each successive fifth compounds the error by a factor of 3.</p>

  <p>Letting Δ = 7153 / 524288, the deviation for each successive note is:</p>

  <ul>
    <li>C = 3⁰ × Δ ≈ 0.01</li>
    <li>G = 3¹ × Δ ≈ 0.04</li>
    <li>D = 3² × Δ ≈ 0.12</li>
    <li>A = 3³ × Δ ≈ 0.37</li>
    <li>E = 3⁴ × Δ ≈ 1.11</li>
    <li>B = 3⁵ × Δ ≈ 3.32</li>
  </ul>

  <p>The system of pure fifths (powers of 3) and pure octaves (powers of 2) cannot close. Even at their nearest alignment, 3¹² ≠ 2¹⁹. The residual persists without resolution, opening the circle of fifths into an ascending spiral that generates six additional tones beyond the original twelve. Musical instruments must therefore be tuned to the specific scales in which they are played.</p>

  <hr />

  <!-- ══════════════════════════════════════ -->
  <!-- IV. A CORRECTION OF NAMES              -->
  <!-- ══════════════════════════════════════ -->
  <h2>A Correction of Names</h2>

  <p>The conventional system of note names carries no inner logic. It has been used throughout this document thus far as a concession to familiarity; it will serve no further.</p>

  <p>A sound nomenclature must satisfy two conditions: it must reflect the order of generation, and it must remain legible when the tones are arranged by proximity of pitch. The inherited system satisfies neither, obscuring in the process the very principles established in the preceding sections.</p>

  <p>The first generated tone should bear the first letter of the alphabet. The first seven tones produced form the <em>primary set</em> — the maximum a scale may contain — and their names require no accidental. The five tones generated thereafter form the <em>secondary set</em>, occupying the intermediate positions of the chromatic circle; these require one.</p>

  <p>On a keyboard, the primary set falls upon the white keys; the secondary, upon the black.</p>

  <p>Under the conventional system, the note designated F♯ belongs to the primary set and should therefore carry no accidental. The note designated F belongs to the secondary set and should. The present convention has it precisely inverted.</p>

  <p>The corrected assignment of names to generated tones is as follows:</p>

  <ul>
    <li>3⁰ Hz  =  A</li>
    <li>3¹ Hz  =  E</li>
    <li>3² Hz  =  B</li>
    <li>3³ Hz  =  F</li>
    <li>3⁴ Hz  =  C</li>
    <li>3⁵ Hz  =  G</li>
    <li>3⁶ Hz  =  D</li>
    <li>3⁷ Hz  =  A♯</li>
    <li>3⁸ Hz  =  E♯</li>
    <li>3⁹ Hz  =  B♯</li>
    <li>3¹⁰ Hz  =  F♯</li>
    <li>3¹¹ Hz  =  C♯</li>
  </ul>

  <p>And for the extra tones of the ascending spiral, where Δ = 7153 / 524288 ≈ 0.013643:</p>

  <ul>
    <li>3⁰ × Δ Hz  =  Ax</li>
    <li>3¹ × Δ Hz  =  Ex</li>
    <li>3² × Δ Hz  =  Bx</li>
    <li>3³ × Δ Hz  =  Fx</li>
    <li>3⁴ × Δ Hz  =  Cx</li>
    <li>3⁵ × Δ Hz  =  Gx</li>
  </ul>

  <p>All sections that follow use this corrected nomenclature.</p>

  <p>The musical modes inherit the same problem as the notes — names assigned by geography and history rather than by principle. This document establishes, in the sections that follow, that the seven modes correspond to the seven wandering stars. It is fitting, then, that they bear their names. The corrected designations are as follows:</p>

  <ul>
    <li>Mode I — Lunar <em>(formerly Lydian)</em></li>
    <li>Mode II — Mercurial <em>(formerly Mixolydian)</em></li>
    <li>Mode III — Venusian <em>(formerly Aeolian)</em></li>
    <li>Mode IV — Solar <em>(formerly Locrian)</em></li>
    <li>Mode V — Martial <em>(formerly Ionian)</em></li>
    <li>Mode VI — Jovial <em>(formerly Dorian)</em></li>
    <li>Mode VII — Saturnine <em>(formerly Phrygian)</em></li>
  </ul>

  <p>The old names are retained in parentheses for reference only.</p>

  <img src="/images/Ptolemaicsystem-small.png" alt="Ptolemaic System" />

  <hr />

  <!-- ══════════════════════════════════════ -->
  <!-- V. GRAPHIC EVIDENCE                    -->
  <!-- ══════════════════════════════════════ -->
  <h2>Graphic Evidence</h2>

  <p>In 1787, Ernst Chladni demonstrated that sound possesses a geometric dimension. By drawing a violin bow along the edge of a flour-dusted plate, he observed symmetrical patterns emerge — the flour migrating to the nodal lines, where the surface was still.</p>

  <img src="/images/Bowing_chladni_plate.png" alt="Cymatics - Chladni Plate" />

  <p>In the 20th century, Hans Jenny coined the term <em>cymatics</em> to describe such acoustic phenomena. The hidden geometry of frequency is thereby revealed: certain tones resolve into clear, coherent forms; other... not so much.</p>

  <img src="/images/Sonoluminescence3.jpg" alt="Sonoiluminescence - Sulfuric Acid" />

  <p>The note A in this system, at its fourth octave, carries a frequency of 432 Hz (3³ × 2⁴). In cymatics experiments it yields a precise and beautiful geometric figure. The Stuttgart standard pitch of 440 Hz produces no such clarity — only disorder made comfortable by long familiarity.</p>

  <div class="video-wrap">
    <iframe
      src="https://www.youtube.com/embed/zS3DMYF-n1o"
      title="Cymatics"
      loading="lazy"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen
    ></iframe>
  </div>

  <div class="video-wrap">
    <iframe
      src="https://www.youtube.com/embed/Up3X5dtnCus"
      title="Cymatics 2"
      loading="lazy"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen
    ></iframe>
  </div>

  <hr />

  <!-- ══════════════════════════════════════ -->
  <!-- VI. THE SPECTRAL WHEEL                 -->
  <!-- ══════════════════════════════════════ -->
  <h2>The Spectral Wheel</h2>

  <p>What has been done with sound can be done with colour.</p>

  <p>A colour is defined by its wavelength in nanometres and its frequency in terahertz. A dispersive prism separates white light into its constituent spectral colours — the rainbow. Isaac Newton demonstrated this in the 17th century. White light is the sum of all spectral colours, or more precisely, the combination of the three primary ones.</p>

  <img src="/images/Dispersive_prism.png" alt="Issac Newton - Dispersive Prism" />

  <p>Those three primaries — from which any other spectral colour can be composed, confirming once more that three is the number of creation — are spectral red, spectral green, and spectral blue. Their order is significant: red carries the lowest frequency, blue the highest.</p>

  <img src="/images/Newton's_color_circle.png" alt="Issac Newton - Color Circle" />

  <p>Colours are described by the ratios in which they contain each primary:</p>

  <ul>
    <li>Red: 1:0:0</li>
    <li>Green: 0:1:0</li>
    <li>Blue: 0:0:1</li>
    <li>Yellow: 1:1:0</li>
    <li>Azure: 0:1:1</li>
    <li>Cyclamen: 1:0:1</li>
  </ul>

  <p>To reach the intermediate hues between these six, a further ratio is required:</p>

  <ul>
    <li>Medlar: 2:1:0</li>
    <li>Olive: 1:2:0</li>
    <li>Teal: 0:2:1</li>
    <li>Indigo: 0:1:2</li>
    <li>Lavender: 1:0:2</li>
    <li>Mulberry: 2:0:1</li>
  </ul>

  <p>These twelve ratios divide the hue circle into equal parts.</p>

  <hr />

  <!-- ══════════════════════════════════════ -->
  <!-- VII. THE SCALE OF SHADES               -->
  <!-- ══════════════════════════════════════ -->
  <h2>The Scale of Shades</h2>

  <p>The ratio 1:1:1 yields the achromatic colours. These belong not to a circle but to a linear scale of seven degrees: black, pitch-black, iron gray, dark gray, gray, light gray, silver, and white.</p>

  <img src="/images/moonbow_at_lower_Yosemite_fall.jpg" alt="Moonbow at lower Yosemite Fall" />

  <hr />

  <!-- ══════════════════════════════════════ -->
  <!-- VIII. THE COLOUR GYROSCOPE             -->
  <!-- ══════════════════════════════════════ -->
  <h2>The Colour Gyroscope</h2>

  <p>A complete palette demands more than fully saturated and achromatic colours. From the spectral hue circle, three further circles are born by the successive application of black, gray, and white light. The full palette, expressed in both HSL and RGB, is as follows:</p>

  <!-- ── Spectral Colour Wheel ── -->
  <p><strong>Spectral Colour Wheel</strong> <em>— full saturation, mid lightness (100% / 50%)</em></p>
  <div class="swatch-strip">
    {#each COLOR_PALETTES.wheel as { name, variable }}
      <div class="swatch" style="background-color: var({variable});" title={name}></div>
    {/each}
  </div>
  <pre>
red        hsl(0,   100%, 50%)  → rgb(255,   0,   0)
medlar     hsl(30,  100%, 50%)  → rgb(255, 128,   0)
yellow     hsl(60,  100%, 50%)  → rgb(255, 255,   0)
olive      hsl(90,  100%, 50%)  → rgb(128, 255,   0)
green      hsl(120, 100%, 50%)  → rgb(  0, 255,   0)
teal       hsl(150, 100%, 50%)  → rgb(  0, 255, 128)
azure      hsl(180, 100%, 50%)  → rgb(  0, 255, 255)
indigo     hsl(210, 100%, 50%)  → rgb(  0, 128, 255)
blue       hsl(240, 100%, 50%)  → rgb(  0,   0, 255)
lavender   hsl(270, 100%, 50%)  → rgb(128,   0, 255)
cyclamen   hsl(300, 100%, 50%)  → rgb(255,   0, 255)
mulberry   hsl(330, 100%, 50%)  → rgb(255,   0, 128)</pre>

  <!-- ── Scale of Shades ── -->
  <p><strong>Scale of Shades</strong> <em>— 0% saturation</em></p>
  <div class="swatch-strip">
    {#each COLOR_PALETTES.scale as { name, variable }}
      <div class="swatch" style="background-color: var({variable});" title={name}></div>
    {/each}
  </div>
  <pre>
black       hsl(0, 0%,   0%)  → rgb(  0,   0,   0)
pitch-black hsl(0, 0%,  12%)  → rgb( 31,  31,  31)
iron-gray   hsl(0, 0%,  25%)  → rgb( 64,  64,  64)
dark-gray   hsl(0, 0%,  37%)  → rgb( 94,  94,  94)
gray        hsl(0, 0%,  50%)  → rgb(128, 128, 128)
light-gray  hsl(0, 0%,  62%)  → rgb(158, 158, 158)
silver      hsl(0, 0%,  75%)  → rgb(191, 191, 191)
snow-white  hsl(0, 0%,  88%)  → rgb(224, 224, 224)
white       hsl(0, 0%, 100%)  → rgb(255, 255, 255)</pre>

  <!-- ── Colour Wheel of Darkness ── -->
  <p><strong>Colour Wheel of Darkness</strong> <em>— 50% saturation, 25% lightness</em></p>
  <div class="swatch-strip">
    {#each COLOR_PALETTES.wheel_of_darkness as { name, variable }}
      <div class="swatch" style="background-color: var({variable});" title={name}></div>
    {/each}
  </div>
  <pre>
dark-red        hsl(0,   50%, 25%)  → rgb( 96,  32,  32)
dark-medlar     hsl(30,  50%, 25%)  → rgb( 96,  64,  32)
dark-yellow     hsl(60,  50%, 25%)  → rgb( 96,  96,  32)
dark-olive      hsl(90,  50%, 25%)  → rgb( 64,  96,  32)
dark-green      hsl(120, 50%, 25%)  → rgb( 32,  96,  32)
dark-teal       hsl(150, 50%, 25%)  → rgb( 32,  96,  64)
dark-azure      hsl(180, 50%, 25%)  → rgb( 32,  96,  96)
dark-indigo     hsl(210, 50%, 25%)  → rgb( 32,  64,  96)
dark-blue       hsl(240, 50%, 25%)  → rgb( 32,  32,  96)
dark-lavender   hsl(270, 50%, 25%)  → rgb( 64,  32,  96)
dark-cyclamen   hsl(300, 50%, 25%)  → rgb( 96,  32,  96)
dark-mulberry   hsl(330, 50%, 25%)  → rgb( 96,  32,  64)</pre>

  <!-- ── Colour Wheel of Ghost ── -->
  <p><strong>Colour Wheel of Ghost</strong> <em>— 50% saturation, 50% lightness</em></p>
  <div class="swatch-strip">
    {#each COLOR_PALETTES.wheel_of_ghost as { name, variable }}
      <div class="swatch" style="background-color: var({variable});" title={name}></div>
    {/each}
  </div>
  <pre>
ghost-red        hsl(0,   50%, 50%)  → rgb(191,  64,  64)
ghost-medlar     hsl(30,  50%, 50%)  → rgb(191, 128,  64)
ghost-yellow     hsl(60,  50%, 50%)  → rgb(191, 191,  64)
ghost-olive      hsl(90,  50%, 50%)  → rgb(128, 191,  64)
ghost-green      hsl(120, 50%, 50%)  → rgb( 64, 191,  64)
ghost-teal       hsl(150, 50%, 50%)  → rgb( 64, 191, 128)
ghost-azure      hsl(180, 50%, 50%)  → rgb( 64, 191, 191)
ghost-indigo     hsl(210, 50%, 50%)  → rgb( 64, 128, 191)
ghost-blue       hsl(240, 50%, 50%)  → rgb( 64,  64, 191)
ghost-lavender   hsl(270, 50%, 50%)  → rgb(128,  64, 191)
ghost-cyclamen   hsl(300, 50%, 50%)  → rgb(191,  64, 191)
ghost-mulberry   hsl(330, 50%, 50%)  → rgb(191,  64, 128)</pre>

  <!-- ── Colour Wheel of Light ── -->
  <p><strong>Colour Wheel of Light</strong> <em>— 50% saturation, 75% lightness</em></p>
  <div class="swatch-strip">
    {#each COLOR_PALETTES.wheel_of_light as { name, variable }}
      <div class="swatch" style="background-color: var({variable});" title={name}></div>
    {/each}
  </div>
  <pre>
light-red        hsl(0,   50%, 75%)  → rgb(223, 159, 159)
light-medlar     hsl(30,  50%, 75%)  → rgb(223, 191, 159)
light-yellow     hsl(60,  50%, 75%)  → rgb(223, 223, 159)
light-olive      hsl(90,  50%, 75%)  → rgb(191, 223, 159)
light-green      hsl(120, 50%, 75%)  → rgb(159, 223, 159)
light-teal       hsl(150, 50%, 75%)  → rgb(159, 223, 191)
light-azure      hsl(180, 50%, 75%)  → rgb(159, 223, 223)
light-indigo     hsl(210, 50%, 75%)  → rgb(159, 191, 223)
light-blue       hsl(240, 50%, 75%)  → rgb(159, 159, 223)
light-lavender   hsl(270, 50%, 75%)  → rgb(191, 159, 223)
light-cyclamen   hsl(300, 50%, 75%)  → rgb(223, 159, 223)
light-mulberry   hsl(330, 50%, 75%)  → rgb(223, 159, 191)</pre>

  <hr />

  <!-- ══════════════════════════════════════ -->
  <!-- IX. CELESTIAL THEORY                   -->
  <!-- ══════════════════════════════════════ -->
  <h2>Celestial Theory</h2>

  <p>Before the stars are measured, they must first be heard.</p>

  <blockquote>"When the morning stars sang together, and all the sons of God shouted for joy?"</blockquote>
  <p class="cite">— Job 38:7</p>

  <p>The tradition called <em>musica universalis</em> — the harmony of the spheres — holds that the motions of celestial bodies are expressions of musical proportion, and that the cosmos is, at its root, a sonic order. The idea is traced to Pythagoras, who taught that the distances and velocities of the wandering stars correspond to musical intervals, producing a vast and inaudible harmony. Plato preserved it in the <em>Republic</em>, where the Sirens sing a single note upon each celestial sphere. It passed through the Neoplatonists, through the medieval quadrivium, and arrived — transformed but intact — at the desk of Johannes Kepler.</p>

  <img src="/images/Ioanniskepplerih00kepl_0081.jpg" alt="Ioannis Keppler - Platonic Solids" />

  <p>In his <em>Harmonices Mundi</em> (1619), Kepler calculated the angular velocity of each planet at perihelion and aphelion — its fastest and slowest points in orbit — and derived the musical interval each planet traces across the sky. Saturn spans a minor third; Jupiter, the same. Mars spans a fifth. The Earth, whose variation in speed is the most constrained of all, produces a single semitone — the interval between <em>mi</em> and <em>fa</em>, which Kepler read as <em>miseria</em>: misery. He then assigned a modal character to each wandering star.</p>

  <img src="/images/Kepler_Mars_retrograde.jpg" alt="Ioannis Keppler - Mars' Retrograde Motion" />

  <p>The present work stands in this lineage, but moves in the opposite direction. This system begins with God's simplest gift — the heartbeat, the fifth, the octave — and builds upward from first principles, from the darkness of sin toward the light of the heavenly order. The ancients heard harmony from without. This is an attempt to construct it from within.</p>

  <h3>Sonoluminescence</h3>

  <p>Sonoluminescence is the emission of light from imploding bubbles in a liquid excited by sound — luminescence induced by acoustic energy. It was accidentally discovered in 1934 at the University of Cologne by Hermann Frenzel and H. Schultes during sonar research.</p>

  <p>The phenomenon has since been observed in nature: the pistol shrimp is the first known creature to produce light by this means, collapsing cavitation bubbles with its claw to generate a flash intense enough to stun or kill prey.</p>

  <img src="/images/Pistol-Shrimp.jpg" alt="Sonoiluminescence - Pistol Shrimp" />

  <p>This is not a curiosity. It is evidence that light can be born from sound.</p>

  <div class="video-wrap">
    <iframe
      src="https://www.youtube.com/embed/ONQlTMUYCW4?start=8"
      title="Sonoluminescence"
      loading="lazy"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen
    ></iframe>
  </div>

  <blockquote>"And God said, 'Let there be a canopy in the midst of the waters, and let it separate the waters from the waters.' And God made the canopy and separated the waters that were under the expanse from the waters that were above the expanse. And it was so. And God called the expanse Heaven. And there was evening and there was morning, the second day."</blockquote>
  <p class="cite">— Genesis 1:6–8</p>

  <p>It is possible that the stars are singing angels — or their reflection of some kind.</p>

  <img src="/images/Nikon P1000 - Zooming On A Star!.jpg" alt="NikonP1000 Star Zoom" />

  <img src="/images/Ezekiel's_vision.jpg" alt="Ezekiel's Vision" />

  <blockquote>"As for the appearance of the wheels and their construction: their appearance was like the gleaming of beryl. And the four had the same likeness, their appearance and construction being as it were a wheel within a wheel."</blockquote>
  <p class="cite">— Ezekiel 1:16</p>

  <p>Perhaps the stars are bound to harmonic intervals by the ancient analogy of microcosm and macrocosm.</p>

  <blockquote>"Your kingdom come, your will be done, on earth as it is in heaven."</blockquote>
  <p class="cite">— Matthew 6:10</p>

  <p>The zodiacal plane is the path the Sun traces across the sky. Traditionally divided into twelve parts, its constellations correspond to the twelve musical notes and the twelve spectral colours alike.</p>

  <p>The zodiac opens with Aries — the spring equinox, when Christ was crucified — followed by Taurus and Gemini. Cancer marks the summer solstice, followed by Leo and Virgo. Libra falls at the autumn equinox, followed by Scorpius and Sagittarius. Capricornus holds the winter solstice, Aquarius follows, and the cycle closes with Pisces.</p>

  <img src="/images/Beit_alfa01.jpg" alt="The Zodiac" />

  <p>The degrees of a scale — and the achromatic shades — find further correspondence in the wandering stars: those visible to the naked eye that move across the firmament against the fixed constellations. Ordered from swiftest to slowest, by sidereal motion and retrograde duration alike, they are the Moon ☽, Mercury ☿, Venus ♀, the Sun ☉, Mars ♂, Jupiter ♃, and Saturn ♄.</p>

  <p>Their measured properties are as follows:</p>

  <!-- Derived from WANDERING_STARS (stars.ts) -->
  <table class="table-wrap">
    <thead>
      <tr>
        <th>Wandering Star (Old Croatian name)</th>
        <th>Angular Size</th>
        <th>Speed (°/day)</th>
        <th>Sidereal Period (days)</th>
        <th>Synodic Period (days)</th>
        <th>Retrograde (days)</th>
      </tr>
    </thead>
    <tbody>
      {#each WANDERING_STARS as star}
        <tr>
          <td>{star.name} {star.symbol}{star.ime !== '(Unknown)' ? ` (${star.ime})` : ''}</td>
          <td>{star.angularSizeRange}</td>
          <td>{star.speedDegPerDay}</td>
          <td>{star.siderealDanceDays}</td>
          <td>{star.solarDanceDays || '—'}</td>
          <td>{star.retrogradeDays !== 0 ? `~${star.retrogradeDays}` : '—'}</td>
        </tr>
      {/each}
    </tbody>
  </table>

  <p>This sequence is rich in pattern and has been preserved since antiquity — perhaps for reasons deeper than we yet understand.</p>

  <hr />

  <!-- ══════════════════════════════════════ -->
  <!-- X. THE NUMBERS                         -->
  <!-- ══════════════════════════════════════ -->
  <h2>The Numbers</h2>

  <p>The system assembled in the preceding sections is governed by two numbers. Twelve commands the circle — the chromatic compass, the hue wheel, the zodiac. Seven commands the living sequence within it — the modes, the scale, the degrees of shade, the wandering stars. Their relationship is the hidden architecture of the entire design.</p>

  <img src="/images/Tabernakel.jpg" alt="The Twelve Tribes of Isreael - Tabernacle" />

  <h3>Twelve</h3>

  <p>Twelve is the third superior highly composite number, the third colossally abundant number, and the fifth highly composite number. It is evenly divisible by 1, 2, 3, 4, 6, and 12 — an extraordinary range for so small a quantity. It is the smallest abundant number, a semiperfect number, a refactorable number, and a Pell number. It is the lesser of the two known <em>sublime numbers</em>: those whose divisor count is perfect and whose divisors sum to a perfect number in turn.</p>

  <p>Its geometric character is equally remarkable. The dodecagon — twelve-sided — is the largest regular polygon that tiles the plane alongside other regular polygons. A regular dodecahedron has twelve pentagonal faces. Both the cube and the octahedron carry twelve edges; the icosahedron, twelve vertices. In three dimensions, twelve is the <em>kissing number</em> — the precise count of unit spheres that can simultaneously touch a central one. Both cubic and hexagonal close packings, the densest possible arrangements of spheres in space, place each sphere in contact with exactly twelve neighbours.</p>

  <p>Twelve appears 147 times in Scripture. Ishmael has twelve sons; Jacob, twelve sons who become the twelve tribes of Israel. Christ called twelve Apostles, and when one fell, the assembly was immediately restored to twelve. The Old Testament contains twelve Minor Prophets. The Book of Revelation is threaded with the figure: a woman crowned with twelve stars; twelve thousand sealed from each of twelve tribes, yielding 144,000 in all — the square of twelve, multiplied by a thousand.</p>

  <img src="/images/Mosaic_Tribes.jpg" alt="The Twelve Tribes of Isreael - Coat of Arms" />

  <blockquote>"Through the middle of the street of the city; also, on either side of the river, the tree of life with its twelve kinds of fruit, yielding its fruit each month. The leaves of the tree were for the healing of the nations."</blockquote>
  <p class="cite">— Revelation 22:2</p>

  <h3>Seven</h3>

  <p>Seven is the fourth prime — and among the most singular. It is a <em>Mersenne prime</em> (2³ − 1 = 7) and a <em>double Mersenne prime</em>, its exponent 3 being Mersenne as well. It is a Newman–Shanks–Williams prime, a safe prime, a lucky prime, a happy prime — and the only number simultaneously Mersenne and safe. It is the lowest natural number that cannot be expressed as the sum of the squares of three integers. In this sense it stands irreducibly apart from all that precede it.</p>

  <p>The heptagon is the first regular polygon that resists classical construction — compass and straightedge cannot build it. Where four, five, and six yield to those ancient instruments, seven withholds itself. There are precisely seven frieze groups in the plane: the seven fundamental symmetries by which a pattern may repeat along a line.</p>

  <p>Seven's most immediate presence in human life is time itself. The days of the week descend directly from the seven wandering stars, each day assigned to its celestial patron in antiquity. The correspondence is legible in every modern tongue: Sunday for the Sun, Monday for the Moon, Saturday for Saturn. In the Germanic languages, the remaining four bear the names of Norse divines equated with the classical planets — Tuesday for Mars (Týr), Wednesday for Mercury (Wōden), Thursday for Jupiter (Thor), Friday for Venus (Frigg). In the Romance languages the lineage is yet more transparent: <em>mardi</em> is Mars, <em>mercredi</em> Mercury, <em>jeudi</em> Jupiter, <em>vendredi</em> Venus. Every week, without exception, the seven wandering stars inscribe themselves upon the days of every human life.</p>

  <p>In Scripture, seven is the signature of completion. Creation unfolds across six days and rests on the seventh. The Book of Revelation turns on seven seals, seven trumpets, seven bowls — seven not as the endless ring of twelve, but as the wholeness of a journey brought to its final degree: a scale resolved, a song concluded.</p>

  <img src="/images/Angels_receiving_seven_trumpets_-_Apocalypse_Picture_Book,_Pierpont_Morgan.jpg" alt="The Seven Trumpets" />

  <p>Within this design: seven notes in a scale, seven modes, seven wandering stars, seven degrees of achromatic shade. Twelve is the vessel. Seven is what moves inside it.</p>

  <hr />

  <!-- ══════════════════════════════════════ -->
  <!-- XI. THE SYNTHESIS                      -->
  <!-- ══════════════════════════════════════ -->
  <h2>The Synthesis</h2>

  <p>All that has been established converges here. Three domains — sound, colour, and the celestial order — are governed by the same two numbers and the same two ratios. What follows is the complete correspondence.</p>

  <p>The circle of twelve unites the chromatic notes, the spectral hues, and the signs of the zodiac into a single ring. The sequence begins at Aries — the spring equinox, the first sign, the point of resurrection and renewal.</p>

  <!-- Derived from NEW_NOTES_1_ALL (sounds.ts) + COLOR_PALETTES.wheel (colors.ts)
       + ZODIAC_CONSTELLATIONS (stars.ts) — same index, same correspondence. -->
  <table class="table-wrap">
    <thead>
      <tr><th>Position</th><th>Note</th><th>Colour</th><th>Zodiac Sign</th></tr>
    </thead>
    <tbody>
      {#each circleOfTwelve as { note, color, colorVar, zodiac }, i}
        <tr>
          <td>{i + 1}</td>
          <td>{note}</td>
          <td>
            <span class="color-swatch" style="background-color: var({colorVar});"></span>
            {color}
          </td>
          <td>{zodiac.name} {zodiac.symbol}</td>
        </tr>
      {/each}
    </tbody>
  </table>

  <p>The sequence of seven binds the musical modes, the wandering stars, and the days of the week into one living order. The modes run in their natural succession; the stars are placed against them by sidereal speed, from the swiftest to the most ancient and slow.</p>

  <!-- Derived from NEW_MODES + SCALE_DEGREE_NUMERALS (sounds.ts)
       + WANDERING_STARS (stars.ts). -->
  <table class="table-wrap">
    <thead>
      <tr><th>Degree</th><th>Mode</th><th>Wandering Star</th></tr>
    </thead>
    <tbody>
      {#each sequenceOfSeven as { numeral, mode, star }}
        <tr>
          <td>{numeral}</td>
          <td>{mode}</td>
          <td>{star.name} {star.symbol}{star.ime !== '(Unknown)' ? ` (${star.ime})` : ''}</td>
        </tr>
      {/each}
    </tbody>
  </table>

  <p>Sound, colour, and the wandering stars above are governed by the same two proportions — born from the same heartbeat, the same fifth, the same octave, the same one trinitarian God.</p>

  <img src="/images/Kepler_Optica.jpg" alt="Ioannis Keppler - Optica" />

  <p>This is not a theory about music. Nor is it a theory about colour. It is a claim about the structure of the created world: that harmony is not a matter of taste but of number; that beauty is not completely subjective but measurable, if not by man-made tools, than certainly by a holy intuition; that the same ratios governing a plucked string also govern the turning of the heavens.</p>

  <p>This document has attempted nothing more than to gather those threads, extend them by arithmetic and first principle, and hold them in a single hand. What it describes was not invented. It was recovered and inscribed to this digital monolith.</p>

  <img src="/images/Polaris Time lapse.jpg" alt="Polaris Time Lapse" />

</article>